name: fashion_lens
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  camera: ^0.10.0
  google_mlkit_pose_detection: ^0.12.0
  flutter_secure_storage: ^5.0.2+3
  page_transition: ^2.0.9
  shared_preferences: ^2.0.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/jacket.png
    - assets/images/skirt.png
    - assets/images/jeans.png
    - assets/images/womens_blouse.png
    - assets/images/wedding_dress.png
    - assets/vectors/vector_74_x2.svg
    - assets/vectors/group_16_x2.svg
    - assets/vectors/component_115_x2.svg
    - assets/vectors/wifi_8_x2.svg
    - assets/vectors/vector_81_x2.svg
    - assets/vectors/vector_90_x2.svg
    - assets/vectors/wifi_29_x2.svg
    - assets/vectors/vector_43_x2.svg
    - assets/vectors/group_2_x2.svg
    - assets/vectors/vector_7_x2.svg
    - assets/vectors/vector_26_x2.svg
    - assets/vectors/component_128_x2.svg
    - assets/images/jacket.png
    - assets/images/skirt.png
    - assets/images/jeans.png
    - assets/images/wedding_dress.png
    - assets/images/womens_blouse.png
    - assets/vectors/group_13_x2.svg
    - assets/vectors/vector_69_x2.svg
    - assets/vectors/vector_80_x2.svg
    - assets/vectors/component_18_x2.svg
    - assets/vectors/vector_10_x2.svg
    - assets/vectors/wifi_7_x2.svg
    - assets/vectors/vector_17_x2.svg
    - assets/vectors/group_1_x2.svg
    - assets/vectors/wifi_17_x2.svg
    - assets/vectors/vector_83_x2.svg
    - assets/vectors/component_110_x2.svg
    - assets/vectors/vector_89_x2.svg
    - assets/images/desain_tanpa_judul_83.png
    - assets/vectors/flat_color_iconsgoogle_1_x2.svg
    - assets/vectors/wifi_27_x2.svg
    - assets/vectors/vector_35_x2.svg
    - assets/vectors/vector_6_x2.svg
    - assets/vectors/component_126_x2.svg
    - assets/images/denim_shorts.png
    - assets/images/jeans.png
    - assets/vectors/component_121_x2.svg
    - assets/vectors/wifi_9_x2.svg
    - assets/vectors/vector_61_x2.svg
    - assets/vectors/group_15_x2.svg
    - assets/vectors/vector_95_x2.svg
    - assets/vectors/vector_72_x2.svg
    - assets/images/desain_tanpa_judul_83.png
    - assets/vectors/wifi_22_x2.svg
    - assets/vectors/vector_24_x2.svg
    - assets/vectors/vector_15_x2.svg
    - assets/vectors/vector_31_x2.svg
    - assets/vectors/component_112_x2.svg
    - assets/images/whats_app_image_20240521_at_14131.jpeg
    - assets/images/compact_camera.png
    - assets/vectors/vector_38_x2.svg
    - assets/vectors/component_117_x2.svg
    - assets/vectors/wifi_11_x2.svg
    - assets/vectors/vector_62_x2.svg
    - assets/vectors/vector_8_x2.svg
    - assets/images/denim_shorts.png
    - assets/images/tshirt.png
    - assets/images/sweater.png
    - assets/vectors/vector_41_x2.svg
    - assets/vectors/wifi_x2.svg
    - assets/vectors/component_119_x2.svg
    - assets/vectors/group_4_x2.svg
    - assets/vectors/vector_68_x2.svg
    - assets/vectors/vector_84_x2.svg
    - assets/images/desain_tanpa_judul_83.png
    - assets/vectors/wifi_20_x2.svg
    - assets/vectors/component_15_x2.svg
    - assets/vectors/vector_73_x2.svg
    - assets/vectors/vector_16_x2.svg
    - assets/images/desain_tanpa_judul_83.png
    - assets/vectors/wifi_3_x2.svg
    - assets/vectors/vector_30_x2.svg
    - assets/vectors/component_12_x2.svg
    - assets/vectors/vector_82_x2.svg
    - assets/vectors/flat_color_iconsgoogle_x2.svg
    - assets/images/sweater.png
    - assets/images/tshirt.png
    - assets/images/jeans.png
    - assets/images/jacket.png
    - assets/images/denim_shorts.png
    - assets/vectors/component_19_x2.svg
    - assets/vectors/group_7_x2.svg
    - assets/vectors/vector_85_x2.svg
    - assets/vectors/wifi_16_x2.svg
    - assets/vectors/vector_66_x2.svg
    - assets/vectors/vector_29_x2.svg
    - assets/images/jacket.png
    - assets/images/sweater.png
    - assets/images/denim_shorts.png
    - assets/images/tshirt.png
    - assets/images/jeans.png
    - assets/vectors/vector_87_x2.svg
    - assets/vectors/vector_47_x2.svg
    - assets/vectors/group_6_x2.svg
    - assets/vectors/wifi_12_x2.svg
    - assets/vectors/vector_42_x2.svg
    - assets/vectors/component_116_x2.svg
    - assets/images/wedding_dress.png
    - assets/images/skirt.png
    - assets/images/jacket.png
    - assets/vectors/vector_67_x2.svg
    - assets/vectors/group_12_x2.svg
    - assets/vectors/component_11_x2.svg
    - assets/vectors/vector_12_x2.svg
    - assets/vectors/vector_33_x2.svg
    - assets/vectors/wifi_21_x2.svg
    - assets/vectors/component_1_x2.svg
    - assets/vectors/vector_76_x2.svg
    - assets/vectors/group_3_x2.svg
    - assets/vectors/vector_59_x2.svg
    - assets/vectors/vector_5_x2.svg
    - assets/vectors/wifi_6_x2.svg
    - assets/images/compact_camera.png
    - assets/images/whats_app_image_20240521_at_14131.jpeg
    - assets/vectors/vector_19_x2.svg
    - assets/vectors/vector_44_x2.svg
    - assets/vectors/wifi_18_x2.svg
    - assets/vectors/vector_65_x2.svg
    - assets/vectors/component_113_x2.svg
    - assets/images/jeans.png
    - assets/images/skirt.png
    - assets/images/womens_blouse.png
    - assets/images/wedding_dress.png
    - assets/images/jacket.png
    - assets/vectors/group_9_x2.svg
    - assets/vectors/wifi_13_x2.svg
    - assets/vectors/component_127_x2.svg
    - assets/vectors/vector_60_x2.svg
    - assets/vectors/vector_86_x2.svg
    - assets/vectors/vector_92_x2.svg
    - assets/images/sweater.png
    - assets/images/jeans.png
    - assets/images/tshirt.png
    - assets/images/denim_shorts.png
    - assets/images/jacket.png
    - assets/vectors/wifi_2_x2.svg
    - assets/vectors/component_13_x2.svg
    - assets/vectors/group_8_x2.svg
    - assets/vectors/vector_54_x2.svg
    - assets/vectors/vector_22_x2.svg
    - assets/vectors/vector_4_x2.svg
    - assets/images/desain_tanpa_judul_83.png
    - assets/vectors/vector_77_x2.svg
    - assets/vectors/vector_58_x2.svg
    - assets/vectors/wifi_23_x2.svg
    - assets/vectors/component_114_x2.svg
    - assets/images/jacket.png
    - assets/images/wedding_dress.png
    - assets/images/jeans.png
    - assets/images/skirt.png
    - assets/images/womens_blouse.png
    - assets/vectors/vector_11_x2.svg
    - assets/vectors/vector_32_x2.svg
    - assets/vectors/component_122_x2.svg
    - assets/vectors/vector_63_x2.svg
    - assets/vectors/group_x2.svg
    - assets/vectors/wifi_10_x2.svg
    - assets/images/jacket.png
    - assets/images/jeans.png
    - assets/images/wedding_dress.png
    - assets/images/skirt.png
    - assets/images/womens_blouse.png
    - assets/vectors/vector_64_x2.svg
    - assets/vectors/group_14_x2.svg
    - assets/vectors/component_129_x2.svg
    - assets/vectors/vector_79_x2.svg
    - assets/vectors/vector_78_x2.svg
    - assets/images/desain_tanpa_judul_83.png
    - assets/vectors/vector_45_x2.svg
    - assets/vectors/wifi_28_x2.svg
    - assets/vectors/vector_75_x2.svg
    - assets/vectors/vector_36_x2.svg
    - assets/vectors/component_123_x2.svg
    - assets/images/compact_camera.png
    - assets/images/whats_app_image_20240521_at_14131.jpeg
    - assets/vectors/vector_21_x2.svg
    - assets/vectors/vector_39_x2.svg
    - assets/vectors/wifi_26_x2.svg
    - assets/vectors/component_124_x2.svg
    - assets/vectors/vector_3_x2.svg
    - assets/vectors/vector_49_x2.svg
    - assets/images/compact_camera.png
    - assets/images/whats_app_image_20240521_at_14131.jpeg
    - assets/vectors/vector_20_x2.svg
    - assets/vectors/vector_34_x2.svg
    - assets/vectors/vector_2_x2.svg
    - assets/vectors/vector_40_x2.svg
    - assets/vectors/component_17_x2.svg
    - assets/vectors/wifi_15_x2.svg
    - assets/images/compact_camera.png
    - assets/images/whats_app_image_20240521_at_14131.jpeg
    - assets/vectors/vector_91_x2.svg
    - assets/vectors/vector_13_x2.svg
    - assets/vectors/wifi_5_x2.svg
    - assets/vectors/component_16_x2.svg
    - assets/vectors/vector_46_x2.svg
    - assets/vectors/vector_70_x2.svg
    - assets/images/user_male.png
    - assets/images/female_user.png
    - assets/vectors/component_125_x2.svg
    - assets/vectors/vector_25_x2.svg
    - assets/vectors/wifi_25_x2.svg
    - assets/vectors/vector_23_x2.svg
    - assets/vectors/group_10_x2.svg
    - assets/vectors/vector_52_x2.svg
    - assets/images/jacket.png
    - assets/images/jeans.png
    - assets/images/denim_shorts.png
    - assets/images/tshirt.png
    - assets/images/sweater.png
    - assets/vectors/wifi_1_x2.svg
    - assets/vectors/component_111_x2.svg
    - assets/vectors/vector_18_x2.svg
    - assets/vectors/vector_48_x2.svg
    - assets/vectors/group_11_x2.svg
    - assets/vectors/vector_1_x2.svg
    - assets/images/desain_tanpa_judul_83.png
    - assets/vectors/vector_55_x2.svg
    - assets/vectors/wifi_24_x2.svg
    - assets/vectors/component_118_x2.svg
    - assets/vectors/vector_50_x2.svg
    - assets/vectors/vector_51_x2.svg
    - assets/images/whats_app_image_20240521_at_14131.jpeg
    - assets/images/compact_camera.png
    - assets/vectors/component_120_x2.svg
    - assets/vectors/vector_14_x2.svg
    - assets/vectors/vector_28_x2.svg
    - assets/vectors/vector_37_x2.svg
    - assets/vectors/wifi_14_x2.svg
    - assets/vectors/vector_93_x2.svg
    - assets/images/women/female_jacket_1.png
    - assets/images/women/female_jacket_2.png
    - assets/images/women/female_jacket_3.png
    - assets/images/women/female_jacket_4.png
    - assets/images/women/female_jacket_5.png
    - assets/images/women/female_jacket_6.png
    - assets/images/women/female_dress_1.png
    - assets/images/women/female_dress_2.png
    - assets/images/women/female_dress_3.png
    - assets/images/women/female_dress_4.png
    - assets/images/women/female_dress_5.png
    - assets/images/women/female_dress_6.png
    - assets/images/women/female_short_1.png
    - assets/images/women/female_short_2.png
    - assets/images/women/female_short_3.png
    - assets/images/women/female_short_4.png
    - assets/images/women/female_short_5.png
    - assets/images/women/female_short_6.png
    - assets/images/women/female_skirt_1.png
    - assets/images/women/female_skirt_2.png
    - assets/images/women/female_skirt_3.png
    - assets/images/women/female_skirt_4.png
    - assets/images/women/female_skirt_5.png
    - assets/images/women/female_skirt_6.png
    - assets/images/women/female_blouse_1.png
    - assets/images/women/female_blouse_2.png
    - assets/images/women/female_blouse_3.png
    - assets/images/women/female_blouse_4.png
    - assets/images/women/female_blouse_5.png
    - assets/images/women/female_blouse_6.png
    - assets/images/men/male_jacket_1.png
    - assets/images/men/male_jacket_2.png
    - assets/images/men/male_jacket_3.png
    - assets/images/men/male_jacket_4.png
    - assets/images/men/male_jacket_5.png
    - assets/images/men/male_jacket_6.png
    - assets/images/men/male_short_1.png
    - assets/images/men/male_short_2.png
    - assets/images/men/male_short_3.png
    - assets/images/men/male_short_4.png
    - assets/images/men/male_short_5.png
    - assets/images/men/male_short_6.png
    - assets/images/men/male_pants_1.png
    - assets/images/men/male_pants_2.png
    - assets/images/men/male_pants_3.png
    - assets/images/men/male_pants_4.png
    - assets/images/men/male_pants_5.png
    - assets/images/men/male_pants_6.png
    - assets/images/men/male_sweatshirt_1.png
    - assets/images/men/male_sweatshirt_2.png
    - assets/images/men/male_sweatshirt_3.png
    - assets/images/men/male_sweatshirt_4.png
    - assets/images/men/male_sweatshirt_5.png
    - assets/images/men/male_sweatshirt_6.png
    - assets/images/men/male_tshirt_1.png
    - assets/images/men/male_tshirt_2.png
    - assets/images/men/male_tshirt_3.png
    - assets/images/men/male_tshirt_4.png
    - assets/images/men/male_tshirt_5.png
    - assets/images/men/male_tshirt_6.png
